version: '3.9'

services:
  app:
    build: .
    container_name: http-server
    restart: on-failure
    network_mode: "host"
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: http-server-mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "BookManagement"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./data/db:/var/lib/mysql

volumes:
  data: