version: '3.9'

services:
  app:
    build: .
    container_name: app
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: http-server-my
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "BookManagement"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./data/db:/var/lib/mysql


  db:
    image: postgres:latest
    container_name: http-server-pgs
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "BookManagement"
    volumes:
      - pg-data:/var/lib/postgresql/data'

  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTIC_HOST: "http://elasticsearch:9200"


  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ./logs:/logs/
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
      - kibana

volumes:
  data:
    driver: local
  pg-data:
    driver: local

